[project]
name = "reward-actflow"
version = "0.1.0"
description = "Reward extension for actflow"
readme = "README.md"
authors = [
    { name = "QuantumDuck", email = "40206399+BrokenDuck@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
reward-actflow = "reward_actflow:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "packages/FlowMol-PyG",
    "packages/diffusiongym",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
